[[pages]]
path = "home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Tools"
icon = "ğŸ§°"
is_section = true

[[pages]]
path = "more_pages/on_page.py"
name = "gRNA input page"
icon = "ğŸ¯"

[[pages]]
path = "more_pages/off_page.py"
name = "Off-target page"
icon = "ğŸ§¬"

[[pages]]
path = "more_pages/convert_databases.py"
name = "Databases"
icon = "ğŸ–´"
